#!/bin/bash
declare XX_CHANNEL_NAME='mychannel'
declare XX_CC_LANGUAGE='go'
declare XX_IMAGETAG='2.0'
declare XX_CC_VERSION='1.0'
declare XX_CC_NAME='simple'
declare XX_DB_TYPE='golevel'
declare XX_CC_PARAMETERS='"init","a","200","b","300"'
declare XX_TRANSIENT_DATA=''
declare XX_EXPOSE_ENDPOINTS='false'
declare XX_BLOCK_NUMBER='newest'
declare XX_CC_PRIVATE='false'
declare XX_CC_POLICY=''
declare XX_CURRENT_ORG=org0.example.com