#!/bin/bash
declare XX_NETWORK_NAME='sandbox'
declare XX_IMAGETAG='2.3.0'
declare XX_EXPOSE_ENDPOINTS='false'
declare XX_CURRENT_STWD=org0.exemplo.com
declare XX_RUN_OUTPUT=minindy
declare XX_TARGET_ENV=DOCKER
