#!/bin/bash
[ ! -d "$(pwd)/vars" ] && mkdir vars
ADDRS=$(ifconfig|grep 'inet '|grep -v '\.1 '|tr -s ' '|awk '{$1=$1};1'|cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -|sed s/addr://g)
if [ -f "$(pwd)/spec.yaml" ]; then
  echo "Using spec file: $(pwd)/spec.yaml"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -v $(pwd)/spec.yaml:/home/spec.yaml -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
else
  echo "Using default spec file"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
fi
