
- name: "Ensure certificate directory is clean"
  file:
    path: "{{ pjroot }}/vars/keyfiles"
    state: "{{ item }}"
  with_items:
    - "absent"
    - "directory"

- name: Make sure that run directory exists
  file:
    path: "{{ pjroot }}/vars/run"
    state: "directory"

- name: Remove the cached node var file
  file:
    path: "{{ pjroot }}/vars/{{ item }}"
    state: "absent"
  with_items:
    - "key_vars.json"
    - "node_vars.json"

- name: "Check if user provided crypto config file exists"
  stat:
    path: "{{ pjroot }}/vars/my-crypto-config.yaml"
  register: cryc

- name: Use the provide crypto-config.yaml file
  copy:
    src: "{{ pjroot }}/vars/my-crypto-config.yaml"
    dest: "{{ pjroot }}/vars/crypto-config.yaml"
  when: cryc.stat.exists == true

- name: Create crypto-config file
  template:
    src: "{{ pjroot }}/playbooks/ops/certgen/templates/crypto-config.j2"
    dest: "{{ pjroot }}/vars/crypto-config.yaml"
  when: cryc.stat.exists == false

- name: Set effecctive release
  set_fact:
    truerelease: "{{ (fabric.release == '1.4') | ternary('1.4.6', fabric.release) }}"

- name: Create config tx file
  template:
    src: "{{ pjroot }}/playbooks/ops/certgen/templates/configtx.j2"
    dest: "{{ pjroot }}/vars/configtx.yaml"

- name: Create certs using openssl
  include_tasks: "orgkeygen.yaml"
  loop: "{{ allorgs }}"
  loop_control:
    loop_var: org

- name: Create certs and channel artifacts script
  template:
    src: "{{ pjroot }}/playbooks/ops/certgen/templates/certtxgen.j2"
    dest: "{{ pjroot }}/vars/run/certtxgen.sh"
    mode: +x

- name: Use fabric tools container to create channel artifacts
  command: >-
    docker run --rm --name tools
    -v /var/run/:/host/var/run
    -v {{ hostroot}}/vars:/etc/hyperledger/fabric
    hyperledger/fabric-tools:{{ fabric.release }} /etc/hyperledger/fabric/run/certtxgen.sh

- name: Upload gensis block for orderers
  when: ISK8S == true and (ordererorgs|length > 0)
  k8s:
    kubeconfig: "{{ pjroot }}/vars/kubeconfig/config"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "genesis-blocks"
        namespace: "{{ NETNAME }}"
      binaryData:
        genesis.block: >-
          {{ lookup('file', pjroot+'/vars/genesis.block', errors='ignore') | b64encode }}

- name: Package all the certs to one file
  archive:
    path: "{{ pjroot }}/vars/keyfiles"
    dest: "{{ pjroot }}/vars/certs.tgz"
