---
- name: "Ensure explorer directory exists"
  file:
    path: "{{ pjroot }}/vars/explorer"
    state: "directory"

- name: Shutdown explorer container from docker
  include_tasks: "dockerapply.yaml"
  when: TARGET_ENV == 'DOCKER'

- name: Shutdown explorer container from k8s
  include_tasks: "k8sapply.yaml"
  when: TARGET_ENV == 'K8SCLASSIC'

- name: "remove explorer directory"
  file:
    path: "{{ pjroot }}/vars/explorer"
    state: "absent"
