---
- name: Clean services in k8s
  include_tasks: "{{ pjroot }}/playbooks/common/k8s-rm-ingress-entry.yaml"
  vars:
     ours: "{{ [ explorer_port ] }}"

- name: Create deployment spec and service file
  template:
    src: "{{ pjroot }}/playbooks/ops/explorerup/k8stemplates/pods.j2"
    dest: "{{ pjroot }}/vars/explorer/pods.yaml"

- name: remove all nodes
  k8s:
    kubeconfig: "{{ pjroot }}/vars/kubeconfig/config"
    state: absent
    src: "{{ pjroot }}/vars/explorer/pods.yaml"
  ignore_errors: yes

- name: remove all configmap
  block:
  - name: remove explorer-configs
    k8s:
      kubeconfig: "{{ pjroot }}/vars/kubeconfig/config"
      state: absent
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: "explorer-configs"
          namespace: "{{ NETNAME }}"
  - name: remove keyfiles
    k8s:
      kubeconfig: "{{ pjroot }}/vars/kubeconfig/config"
      state: absent
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: "keyfiles"
          namespace: "{{ NETNAME }}"
