---
- name: "Check and pull necessary image {{ image }}:{{ fabric.release }}"
  include_tasks: "getimage.yaml"
  loop: "{{ (TARGET_ENV == 'K8SCLASSIC') | ternary(['tools'], ['peer', 'orderer', 'tools', 'ccenv', 'ca']) }}"
  loop_control:
    loop_var: image
  when: status_flag == "Success"

