---
- name: "Ensure portainer directory exists"
  file:
    path: "{{ pjroot }}/vars/portainer"
    state: "directory"

- name: Shutdown portainer container from docker
  include_tasks: "dockerapply.yaml"
  when: ISK8S == false

- name: Shutdown portainer container from k8s
  include_tasks: "k8sapply.yaml"
  when: ISK8S == true

- name: "remove explorer directory"
  file:
    path: "{{ pjroot }}/vars/portainer"
    state: "absent"
