parameters:
  param: []

jobs:
- ${{ each release in parameters.param }}:
  - job: TestFabric${{ release.name }}
    steps:
    - script: sudo apt-get install -y net-tools
      displayName: Install net-tools

    - script: docker build -t hyperledgerlabs/minifab:latest .
      displayName: 'Build up the minifabric container'

    - script: ./minifab up -i ${{ release.number }}
      displayName: 'Setup minifabric network'

    - script: ./minifab cleanup
      displayName: 'Tear down the network'
